### ISSUE TITLE
initialization error

### ISSUE THREAD

**Issue by soufianebenyaala** [basnetjiten/flutter_gcaptcha_v3#16]
E/flutter ( 7047): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'controller' has not been initialized.
E/flutter ( 7047): #0      RecaptchaHandler.controller (package:flutter_gcaptcha_v3/recaptca_config.dart)
E/flutter ( 7047): #1      RecaptchaHandler.executeV3 (package:flutter_gcaptcha_v3/recaptca_config.dart:45:16)

In the executeV3 method, you're trying to run JavaScript on the controller (WebViewController) without checking if it's initialized.

**Comment by basnetjiten** [comment]
Hi @soufianebenyaala this should be resolved in the latest release.

**Comment by chenhaomun** [comment]
Hi, @basnetjiten I'm trying on v2.1.1 but the problem seems still exist.

> LateInitializationError: Field 'controller' has not been initialized. 
#0      RecaptchaHandler.controller (package:flutter_gcaptcha_v3/recaptca_config.dart)
I/flutter (13283): #1      RecaptchaHandler.executeV3 (package:flutter_gcaptcha_v3/recaptca_config.dart:45:16)

**Comment by chenhaomun** [comment]
> Hi, @basnetjiten I'm trying on v2.1.1 but the problem seems still exist.
> 
> > LateInitializationError: Field 'controller' has not been initialized.
> > #0      RecaptchaHandler.controller (package:flutter_gcaptcha_v3/recaptca_config.dart)
> > I/flutter (13283): #1      RecaptchaHandler.executeV3 (package:flutter_gcaptcha_v3/recaptca_config.dart:45:16)

The problem can be resolved by including `ReCaptchaWebView` in my widget but is it mandatory to include in the view? The example code doesn't seems highlighting this.
